CREW_TYPES = ["DRIVER", "MECHANIC", "STRATEGIST", "ENGINEER"]
MISSION_TYPES = ["DELIVERY", "RESCUE", "ESCORT", "SMUGGLE"]
VEHICLE_TYPES = ["CAR", "BIKE", "TRUCK"]

DEFAULT_CASH_BALANCE = 0.0
MIN_SKILL = 0
MAX_SKILL = 100

